name: Poll Upstream

on: push

jobs:
  get-latest-commit:
    runs-on: ubuntu-latest
    outputs:
      has_changed: ${{ steps.get-latest-commit.outputs.has_changed }}
      latest_commit: ${{ steps.get-latest-commit.outputs.latest_commit }}
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SCOPED_TOKEN }}
      - name: Compare Commit Hashes
        id: get-latest-commit
        run: |
          api=https://api.github.com/repos/fkling/astexplorer/commits?per_page=1
          latest_commit=$(curl -sL $api | jq -r ".[0].sha" | tr -d '[:space:]')
          last_known_commit=$(cat upstream-latest.txt | tr -d '[:space:]')
          commit_hash_regex="[0-9a-z]{40}"

          if ! [[ $latest_commit =~ $commit_hash_regex ]]; then
            echo "Upstream Commit Hash $latest_commit is invalid"
            exit 1
          fi

          if ! [[ $last_known_commit =~ $commit_hash_regex ]]; then
            echo "Local Commit Hash $last_known_commit is invalid"
            exit 1
          fi

          if [[ $latest_commit = $last_known_commit ]]; then
            echo "Commit Hash $last_known_commit is still the newest"
            exit 0
          fi

          echo ::set-output name=has_changed::true
          echo ::set-output name=latest_commit::$latest_commit

          echo "Commit Hash $latest_commit is now the newest"
          echo $latest_commit > upstream-latest.txt
  display-if-changed:
    runs-on: ubuntu-latest
    needs: get-latest-commit
    if: needs.get-latest-commit.outputs.has_changed == true
    steps:
      - run: echo ${{needs.get-latest-commit.outputs.has_changed}} ${{needs.get-latest-commit.outputs.latest_commit}}
  display-if-unchanged:
    runs-on: ubuntu-latest
    needs: get-latest-commit
    if: needs.get-latest-commit.outputs.has_changed != true
    steps:
      - run: echo ${{needs.get-latest-commit.outputs.has_changed}} ${{needs.get-latest-commit.outputs.latest_commit}}
