name: Get Latest Upstream Version

on: push

jobs:
  get-latest-commit:
    runs-on: ubuntu-latest
    outputs:
      latest_commit: ${{ steps.get-latest-commit.outputs.latest_commit }}
      pr_branch_name: ${{ steps.get-latest-commit.outputs.pr_branch_name }}
      pr_exists: ${{ steps.get-latest-commit.outputs.pr_exists }}
      short_hash: ${{ steps.get-latest-commit.outputs.short_hash }}
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SCOPED_TOKEN }}
      - name: Compare Commit Hashes
        id: get-latest-commit
        run: |
          commits_api=https://api.github.com/repos/fkling/astexplorer/commits?per_page=1
          latest_commit=$(curl -sL $commits_api | jq -r ".[0].sha" | tr -d '[:space:]')
          last_known_commit=$(cat upstream-latest.txt | tr -d '[:space:]')
          commit_hash_regex="[0-9a-z]{40}"

          if ! [[ $latest_commit =~ $commit_hash_regex ]]; then
            echo "Upstream Commit Hash $latest_commit is invalid"
            exit 1
          fi

          if ! [[ $last_known_commit =~ $commit_hash_regex ]]; then
            echo "Local Commit Hash $last_known_commit is invalid"
            exit 1
          fi

          if [[ $latest_commit = $last_known_commit ]]; then
            echo "Commit Hash $last_known_commit is still the newest"
            exit 0
          fi

          this_repo=${{github.repository}}
          short_hash=$(echo $latest_commit | cut -c1-10)
          pr_branch_name=upstream-$short_hash

          branches_api=https://api.github.com/repos/$this_repo/branches/$pr_branch_name
          branch_name_in_response=$(curl -sL $branches_api | jq -r ".name" | tr -d '[:space:]')

          if [[ $branch_name_in_response = $pr_branch_name ]]; then
            echo "PR exists for $last_known_commit"
            echo ::set-output name=pr_exists::true
            exit 0
          fi

          echo ::set-output name=latest_commit::$latest_commit
          echo ::set-output name=pr_branch_name::$pr_branch_name
          echo ::set-output name=short_hash::$short_hash
  pull-latest:
    runs-on: ubuntu-latest
    needs: get-latest-commit
    if: needs.get-latest-commit.outputs.pr_exists != 'true'
    steps:
      - uses: actions/checkout@v2
      - name: Clone Upstream
        run: |
          rm -rf ./astexplorer
          git clone https://github.com/fkling/astexplorer.git
          rm -rf ./vendor
          mkdir -p ./vendor/astexplorer
          mv ./astexplorer/website ./vendor/astexplorer
          rm -rf ./astexplorer
          git status
      - name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.REPO_SCOPED_TOKEN }}
          commit-message: 'feat(astexplorer): pull latest astexplorer.net'
          committer: Jamie Mason <jamie@foldleft.io>
          author: Jamie Mason <jamie@foldleft.io>
          title: 'Pull ${{needs.get-latest-commit.outputs.short_hash}}'
      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ env.PULL_REQUEST_NUMBER }}"
          echo "Pull Request Number - ${{ steps.create-pr.outputs.pr_number }}"
